server:
  port: 8080 # Cong chay app
  servlet:
    context-path: /hotel-booking


logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    your.package.name: DEBUG


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hotel_booking"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # auto update schema
    show-sql: true

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: nthoc2017.thcsbth@gmail.com
    password: "rljtuyizkwcurjhr"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



jwt:
  signerKey: "/q/Ur0Q2M4h8Csuu67iSpYIg3JlpLD7Ex6nZZMvbt9QvcK0RDwpKtAIIg86jRKSG"
