server:
  port: 8080 # Cong chay app
  servlet:
    context-path: /hotel-booking


logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    your.package.name: DEBUG


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hotel_booking"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # auto update schema
    show-sql: true