server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /hotel-booking


logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    your.package.name: DEBUG


spring:
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # auto update schema
    show-sql: true

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: 18000
  refreshable-duration: 43200

vnpay:
  tmnCode: 1FURF690
  hashSecret: KTFKXYF7KRFE9A7NY9D4CST8QE428O02
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://thaicoh.github.io/hotel-booking-frontend/checkout
  ipnUrl: https://panatrophic-tamesha-ripe.ngrok-free.dev/hotel-booking/api/vnpay/ipn

